version: '3.3'

services:
  php:
    build: ./conf/php/
    env_file:
      - .env
    links:
      - redis
      - postgres
    ports:
      - '9000:9000'
    restart: always
    volumes:
      - ./app:/var/www/html

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
    restart: always

  nginx:
    image: nginx:1.20-alpine
    ports:
      - '80:80'
    restart: always
    links:
      - php
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf

# при изменении перебилдить docker-compose up -d --build
  postgres:
    image: postgres:12.0
    ports:
      - '5432:5432'
    restart: always
#    env_file:
#      - app/.env
    environment:
      POSTGRES_PASSWORD: laravelpassword